


# Permalinks
permalink:        pretty

# Setup
title:            HMT text model
tagline:          'A machine model of HMT project editions'
description:      ''


baseurl: '/hmt-textmodel/'


author:
  name:           'Neel Smith'


links:
  - title: Github repo for HMT text model
    url: https://github.com/homermultitext/hmt-textmodel
    external: true
  - title: API docs
    url: http://homermultitext.github.io/hmt-textmodel/api/org/homermultitext/edmodel/index.html
    external: true
  - title: HMT on github
    url: http://homermultitext.github.io/
    external: true
  - title: HMT web
    url: http://www.homermultitext.org/
    external: true
